using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Routecraft.Minecraft.Networking.Packets
{
    public enum PacketType : byte
    {
        KeepAlive           = 0x00,
        LoginRequest        = 0x01,
        LoginAccepted       = 0x01,
        Handshake           = 0x02,
        Chat                = 0x03,
        UpdateTime          = 0x04,
        PlayerInventory     = 0x05,
        SpawnPosition       = 0x06,
        UseEntity           = 0x07,
        UpdateHealth        = 0x08,
        Respawn             = 0x09,
        Flying              = 0x0A,
        PlayerPosition      = 0x0B,
        PlayerLook          = 0x0C,
        PlayerLookMove      = 0x0D,
        BlockDig            = 0x0E,
        Place               = 0x0F,
        BlockItemSwitch     = 0x10,
        Sleep               = 0x11,
        Animation           = 0x12,
        EntityAction        = 0x13,
        NamedEntitySpawn    = 0x14,
        PickupSpawn         = 0x15,
        Collect             = 0x16,
        VehicleSpawn        = 0x17,
        MobSpawn            = 0x18,
        EntityPainting      = 0x19,
        EntityExpOrbPacket  = 0x1A,
        EntityVelocity      = 0x1C,
        DestroyEntity       = 0x1D,
        Entity              = 0x1E,
        RelEntityMove       = 0x1F,
        EntityLook          = 0x20,
        RelEntityMoveLook   = 0x21,
        EntityTeleport      = 0x22,
        EntityStatus        = 0x26,
        AttachEntity        = 0x27,
        EntityMetadata      = 0x28,
        EntityEffect        = 0x29,
        RemoveEntityEffect  = 0x2A,
        Experience          = 0x2B,
        PreChunk            = 0x32,
        MapChunk            = 0x33,
        MultiBlockChange    = 0x34,
        BlockChange         = 0x35,
        PlayNoteBlock       = 0x36,
        Explosion           = 0x3C,
        DoorChange          = 0x3D,
        Bed                 = 0x46,
        Weather             = 0x47,
        OpenWindow          = 0x64,
        CloseWindow         = 0x65,
        WindowClick         = 0x66,
        SetSlot             = 0x67,
        WindowItems         = 0x68,
        UpdateProgressbar   = 0x69,
        Transaction         = 0x6A,
        CreativeSetSlot     = 0x6B,
        EnchantItem         = 0x6C,
        UpdateSign          = 0x82,
        MapData             = 0x83,
        Statistic           = 0xC8,
        PlayerInfo          = 0xC9,
        PluginMessage       = 0xFA,
        ServerPing          = 0xFE,
        Disconnect          = 0xFF
    }
}
